server:
  port: 10011
  servlet:
    session.timeout: 60000
    contextpath: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    driver_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mymovie
    username: root
    password: 156162

    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启sql语句打印ogging.stdout.StdOutImpl
  
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

